In [1]:
import pandas as pd
import numpy as np

In [3]:
# STUDENT ALCOHOL ASSUMPTION

url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv"
df = pd.read_csv(url, sep=",")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [6]:
# Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column
sliced_df = df.loc[:,'school':'guardian']
print(sliced_df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     reason guardian
0    course   mother
1    course   father
2     other   mother
3      home   mother
4      home   father
..      ...      ...
390  course    other
391  course   mother
392  course    other
393  course   mother
394  course   father

[395 rows x 12 columns]

In [12]:
# Step 5. Create a lambda function that will capitalize strings.

cap_df = lambda x: x.capitalize()
df['Mjob'] = df['Mjob'].apply(cap_df)
df['Fjob'] = df['Fjob'].apply(cap_df)

print(df['Mjob'], df['Fjob'])

0       At_home
1       At_home
2       At_home
3        Health
4         Other
         ...
390    Services
391    Services
392       Other
393    Services
394       Other
Name: Mjob, Length: 395, dtype: object 0       Teacher
1         Other
2         Other
3      Services
4         Other
         ...
390    Services
391    Services
392       Other
393       Other
394     At_home
Name: Fjob, Length: 395, dtype: object

In [13]:
print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  Services  Services
391     MS   M   17       U     LE3       T     3     1  Services  Services
392     MS   M   21       R     GT3       T     1     1     Other     Other
393     MS   M   18       R     LE3       T     3     2  Services     Other
394     MS   M   19       U     LE3       T     1     1     Other   At_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]

In [19]:
# Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker 
# (Consider majority as older than 17 years old)

def majority(x):
    if x > 17:
        return True
    else:
        return False

df['legal_drinker'] = df['age'].apply(majority)

df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,3,4,1,1,3,6,5,6,6,True
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,3,3,1,1,3,4,5,5,6,False
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,3,2,2,3,3,10,7,8,10,False
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,2,2,1,1,5,2,15,14,15,False
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,3,2,1,2,5,4,6,10,10,False
5,GP,M,16,U,LE3,T,4,3,Services,Other,...,4,2,1,2,5,10,15,15,15,False
6,GP,M,16,U,LE3,T,2,2,Other,Other,...,4,4,1,1,3,0,12,12,11,False
7,GP,F,17,U,GT3,A,4,4,Other,Teacher,...,1,4,1,1,1,6,6,5,6,False
8,GP,M,15,U,LE3,A,3,2,Services,Other,...,2,2,1,1,1,0,16,18,19,False
9,GP,M,15,U,GT3,T,3,4,Other,Other,...,5,1,1,1,5,0,14,15,15,False

In [25]:
def times_10(x):
    if type(x) is int or type(x) is float:
        return 10 * x
    return x
df.applymap(times_10).head()

/tmp/ipykernel_6052/1684722386.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(times_10).head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,30,40,10,10,30,60,50,60,60,True
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,30,30,10,10,30,40,50,50,60,False
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,30,20,20,30,30,100,70,80,100,False
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,20,20,10,10,50,20,150,140,150,False
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,20,50,40,60,100,100,False