In [1]:
import pandas as pd

In [7]:
url1 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv'
url2 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv'

cars1 = pd.read_csv(url1, sep=",")
cars2 = pd.read_csv(url2, sep=",")

cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [8]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

In [ ]:
# Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1
# First methond, drop the columns by hands
cars1.drop(['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',	'Unnamed: 12',	'Unnamed: 13'], axis = 1)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

In [16]:
# second methond, auto drop
cars1 = cars1.loc[:, ~cars1.columns.str.contains('Unnamed')]
print(cars1)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70
1    15.0          8           350        165    3693          11.5     70
2    18.0          8           318        150    3436          11.0     70
3    16.0          8           304        150    3433          12.0     70
4    17.0          8           302        140    3449          10.5     70
..    ...        ...           ...        ...     ...           ...    ...
193  24.0          6           200         81    3012          17.6     76
194  22.5          6           232         90    3085          17.6     76
195  29.0          4            85         52    2035          22.2     76
196  24.5          4            98         60    2164          22.1     76
197  29.0          4            90         70    1937          14.2     76

     origin                        car
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
193       1              ford maverick
194       1                 amc hornet
195       1         chevrolet chevette
196       1            chevrolet woody
197       2                  vw rabbit

[198 rows x 9 columns]

In [17]:
# method 3, 创建无 NaN 新列表”
cars1.dropna(axis=1, how='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

In [19]:
# method 4, 正面选择 (Selection)
cars1 =cars1.loc[:, "mpg":"car"]
print(cars1)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70
1    15.0          8           350        165    3693          11.5     70
2    18.0          8           318        150    3436          11.0     70
3    16.0          8           304        150    3433          12.0     70
4    17.0          8           302        140    3449          10.5     70
..    ...        ...           ...        ...     ...           ...    ...
193  24.0          6           200         81    3012          17.6     76
194  22.5          6           232         90    3085          17.6     76
195  29.0          4            85         52    2035          22.2     76
196  24.5          4            98         60    2164          22.1     76
197  29.0          4            90         70    1937          14.2     76

     origin                        car
0         1  chevrolet chevelle malibu
1         1          buick skylark 320
2         1         plymouth satellite
3         1              amc rebel sst
4         1                ford torino
..      ...                        ...
193       1              ford maverick
194       1                 amc hornet
195       1         chevrolet chevette
196       1            chevrolet woody
197       2                  vw rabbit

[198 rows x 9 columns]

In [23]:
# Step 5. What is the number of observations in each dataset?
print(cars1.shape[0])
print(cars2.shape[0])

198
200

In [24]:
cars = pd.concat([cars1, cars2], axis=0, ignore_index=True)
cars.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120,79,2625,18.6,82,1,ford ranger
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10

In [25]:
# Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.
import numpy as np

random_owners = np.random.randint(15000, 73000, size=len(cars))

cars['owners'] = random_owners

print(cars)

      mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0    18.0          8           307        130    3504          12.0     70
1    15.0          8           350        165    3693          11.5     70
2    18.0          8           318        150    3436          11.0     70
3    16.0          8           304        150    3433          12.0     70
4    17.0          8           302        140    3449          10.5     70
..    ...        ...           ...        ...     ...           ...    ...
393  27.0          4           140         86    2790          15.6     82
394  44.0          4            97         52    2130          24.6     82
395  32.0          4           135         84    2295          11.6     82
396  28.0          4           120         79    2625          18.6     82
397  31.0          4           119         82    2720          19.4     82

     origin                        car  owners
0         1  chevrolet chevelle malibu   68639
1         1          buick skylark 320   36558
2         1         plymouth satellite   20270
3         1              amc rebel sst   56958
4         1                ford torino   48624
..      ...                        ...     ...
393       1            ford mustang gl   40321
394       2                  vw pickup   47853
395       1              dodge rampage   24364
396       1                ford ranger   39848
397       1                 chevy s-10   67733

[398 rows x 10 columns]