In [1]:
import pandas as pd
import numpy as np

In [2]:
series1 = pd.Series(np.random.randint(1, 5, size = 100))
series2 = pd.Series(np.random.randint(1, 4, size = 100))
series3 = pd.Series(np.random.randint(10000, 30001, size = 100))

In [7]:
df1 = pd.DataFrame(series1)
df2 = pd.DataFrame(series2)
df3 = pd.DataFrame(series3)

df = pd.concat([series1, series2, series3], axis=1)
df.head()

   0  1      2
0  1  2  22765
1  4  2  10097
2  1  3  10787
3  2  1  12418
4  3  3  14144

In [8]:
# Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter
df.columns = ['bedrs', 'bathrs', 'price_sqr_meter']

df.head()

   bedrs  bathrs  price_sqr_meter
0      1       2            22765
1      4       2            10097
2      1       3            10787
3      2       1            12418
4      3       3            14144

In [13]:
# Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'
bigcolumn = pd.concat([series1, series2, series3], axis = 0).to_frame()

bigcolumn

        0
0       1
1       4
2       1
3       2
4       3
..    ...
95  15219
96  16382
97  22200
98  10929
99  19228

[300 rows x 1 columns]

In [14]:
# Step 6. Oops, it seems it is going only until index 99. Is it true?
bigcolumn.index.max()

99

In [16]:
# Step 7. Reindex the DataFrame so it goes from 0 to 299
bigcolumn.reset_index(drop=True, inplace=True)
bigcolumn

         0
0        1
1        4
2        1
3        2
4        3
..     ...
295  15219
296  16382
297  22200
298  10929
299  19228

[300 rows x 1 columns]